# Generated by Django 5.0.6 on 2025-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userimage',
            name='file_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='userimage',
            name='image_name',
            field=models.CharField(default=models.DateTimeField(auto_now_add=True), max_length=255),
        ),
    ]
