# Generated by Django 5.0.6 on 2025-01-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_settings', to='backend.userimage')),
            ],
        ),
    ]
