# Generated by Django 5.0.6 on 2025-02-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_watermarksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvisibleWatermarkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('embedded_image', models.ImageField(blank=True, null=True, upload_to='uploads/stegnated')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invisible_watermark_settings', to='backend.userimage')),
            ],
        ),
    ]
