# Generated by Django 5.1.5 on 2025-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_invisiblewatermarksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='hidden_watermark_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
