# Generated by Django 5.1.5 on 2025-02-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userimage_hidden_watermark_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('allowed_emails', models.JSONField(blank=True, default=list)),
                ('requires_password', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('allow_sharing', models.BooleanField(default=False)),
                ('max_views', models.IntegerField(default=0)),
                ('current_views', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userimage')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('image_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.imageaccess')),
            ],
        ),
    ]
