# Generated by Django 5.1.5 on 2025-02-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_imageaccess_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageaccess',
            name='allow_sharing',
        ),
        migrations.AlterField(
            model_name='imageaccess',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
