# Generated by Django 5.1.5 on 2025-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_imageaccess_expiration_date_otpsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaccess',
            name='protection_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
