# Generated by Django 5.1.5 on 2025-03-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_imageaccess_protected_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-accessed_at']},
        ),
        migrations.AddField(
            model_name='accesslog',
            name='action_type',
            field=models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('ATTEMPT', 'Access Attempt')], default='VIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageaccess',
            name='user_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='backend.userimage'),
        ),
    ]
