# Generated by Django 5.1.5 on 2025-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_accesslog_options_accesslog_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action_type',
            field=models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('ATTEMPT', 'Access Attempt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
