# Generated by Django 5.1.5 on 2025-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_accesslog_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
