# Generated by Django 5.1.5 on 2025-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_accesslog_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageaccess',
            name='access_name',
            field=models.CharField(default='Access Log', max_length=255),
        ),
    ]
