# Generated by Django 5.1.7 on 2025-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_imageaccess_access_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
