# Generated by Django 5.1.7 on 2025-04-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_userimage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='encryption_perms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='encryption_xor_streams',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
