# Generated by Django 5.1.7 on 2025-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_userimage_encryption_perms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='encryption_perms',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='encryption_xor_streams',
        ),
        migrations.AddField(
            model_name='userimage',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userimage',
            name='perms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userimage',
            name='xor_streams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
