# Generated by Django 5.1.7 on 2025-04-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_userimage_encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='encryption_perms',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='encryption_xor_streams',
        ),
    ]
