# Generated by Django 5.1.7 on 2025-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_userimage_encryption_perms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='encryption_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
