# Generated by Django 5.1.7 on 2025-04-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_userimage_encryption_key_userimage_encryption_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='image_access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.imageaccess'),
        ),
    ]
