# Generated by Django 5.1.7 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_accesslog_image_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='access_rule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_rule_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
