# Generated by Django 5.1.7 on 2025-05-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_accessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaccess',
            name='access_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AIProtectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('protected_image', models.ImageField(blank=True, null=True, upload_to='ai_protected_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_protection', to='backend.userimage')),
            ],
        ),
    ]
