# Generated by Django 5.1.7 on 2025-05-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_imageaccess_access_name_aiprotectionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_access_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_failed_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_successful_access',
            field=models.BooleanField(default=True),
        ),
    ]
