<script>
	import { Brain, Shield, Lock, Settings } from 'lucide-svelte';
</script>

<div class="w-full bg-white px-6 py-16 text-gray-800 lg:px-24">
	<article class="mx-auto max-w-screen-xl space-y-16">
		<!-- Hero Header -->
		<header class="text-center">
			<div class="mb-4 flex justify-center">
				<Brain class="h-10 w-10 text-primary" />
			</div>
			<h1 class="mb-4 text-4xl font-extrabold sm:text-5xl">
				AI Protection: The Future of Image Security
			</h1>
			<p class="mx-auto max-w-2xl text-xl text-gray-600">
				Harness the power of artificial intelligence to protect your images from unauthorized use
				and manipulation. Our advanced AI system watches over your work 24/7.
			</p>
		</header>

		<!-- Intro Section -->
		<section class="grid items-center gap-12 md:grid-cols-2">
			<div>
				<h2 class="mb-4 text-2xl font-semibold">What is AI Protection?</h2>
				<p class="leading-relaxed">
					AI Protection is a cutting-edge security system that uses machine learning to monitor and
					protect your images. It can detect unauthorized use, identify manipulations, and track
					your images across the internet, all while learning and improving over time.
				</p>
			</div>
			<img src="/blog_imgs/ai.png" alt="AI Protection Visualization" class="rounded-lg shadow-md" />
		</section>

		<!-- How It Works -->
		<section class="grid items-center gap-12 md:grid-cols-2">
			<div>
				<h2 class="mb-4 text-2xl font-semibold">How Our AI Protection Works</h2>
				<ol class="list-decimal space-y-4 pl-5">
					<li>Takes your image</li>
					<li>Takes the noise generated by our model</li>
					<li>Applies the noise in the orginal image</li>
				</ol>
			</div>
			<img src="/blog_imgs/uap.png" alt="AI Protection Process" class="rounded-lg shadow" />
		</section>

		<!-- Best Practices -->
		<section>
			<h2 class="mb-6 text-2xl font-semibold">Best Practices for AI Protection</h2>
			<ul class="list-disc space-y-2 pl-6">
				<li>Enable AI protection for all important images in your portfolio.</li>
				<li>Regularly review detection reports and adjust settings as needed.</li>
				<li>Combine AI protection with other security measures for maximum effectiveness.</li>
				<li>Keep your protection settings updated to benefit from the latest AI improvements.</li>
			</ul>
		</section>

		<!-- Use Cases -->
		<section>
			<h2 class="mb-6 text-center text-2xl font-semibold">Where AI Protection Excels</h2>
			<div class="grid gap-6 text-center sm:grid-cols-2 md:grid-cols-3">
				<div class="rounded-lg border p-4">
					<h3 class="text-lg font-semibold">Stock Photography</h3>
					<p class="mt-2 text-sm text-gray-600">
						Monitor and protect your entire stock image portfolio automatically.
					</p>
				</div>
				<div class="rounded-lg border p-4">
					<h3 class="text-lg font-semibold">Brand Assets</h3>
					<p class="mt-2 text-sm text-gray-600">
						Protect company logos and branded imagery from unauthorized use.
					</p>
				</div>
				<div class="rounded-lg border p-4">
					<h3 class="text-lg font-semibold">Artistic Works</h3>
					<p class="mt-2 text-sm text-gray-600">
						Safeguard your digital artwork and photography from theft.
					</p>
				</div>
			</div>
		</section>

		<!-- Behind The Scenes -->
		<section>
			<h2 class="mb-4 text-2xl font-semibold">The Technology Behind AI Protection</h2>
			<p class="leading-relaxed">
				Our AI protection system uses state-of-the-art deep learning models, we use a technique
				known as Adversial Perturbation in which a noise is applied in the image which can confuse
				the ai models.
			</p>
			<p class="mt-4">
				The system is built on a scalable cloud infrastructure that can process millions of images
				daily, ensuring comprehensive protection without compromising performance.
			</p>
		</section>
	</article>
</div>
